name: Vite CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    types:
      - "opened"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v6
        with:
          node-version: 22.20

      - name: Install dependency
        run: npm install
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Run unit test
        run: npm run test
        working-directory: frontend

      - name: Run linting
        run: npm run lint
        working-directory: frontend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: frontend/dist
